services:
  prometheus: # To get metrics from exporters
    container_name: monitoring-prometheus
    image: prom/prometheus
    user: root
    ports:
      - "9090:9090"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules:/etc/prometheus/rules
      - ./probe:/etc/prometheus/probe
      - ./prometheus_data:/prometheus/data
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=5d
      - --storage.tsdb.path=data/
    networks:
      - monitoring

  alert-manager: # To send alert to telegram/discord/...
    container_name: monitoring-alert-manager
    image: prom/alertmanager
    user: root
    ports:
      - "9093:9093"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

  grafana: # To monitor metrics on dashboard
    container_name: monitoring-grafana
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    env_file:
      - .grafana.secret
    networks:
      - monitoring

  aspnet-app: # Thêm service cho ứng dụng ASP.NET Core
    container_name: monitoring-aspnet-app
    image: trien_khai_pham_mem:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Ánh xạ cổng 5000 trên host tới cổng 80 trong container
    networks:
      - monitoring
    depends_on:
      - prometheus  # Đảm bảo Prometheus chạy trước

networks:
  monitoring:
    external: true
    # driver: overlay